### ISSUE TITLE
Add password protection for site

### ISSUE THREAD

**Issue by hqtan** [CodeforAustralia/seechange#4]
## Why
We want to have `seechange.codeforaustralia.org` viewable online so our team can give feedback on current iteration of site, but we may want to prevent the wider public to view the unfinished site at this point in time.

As suggested in #3, employing a password protection feature on our site will allow us to control access to it while we are still working on it.

## What

**As a user** on the site
user will not be able to view the front page, until they provide the correct password

### Options
1. We don't need password protection! There is nothing sensitive to hide from public view. However, it may be a good idea to 'signal' to viewers that this site is still under development. Maybe we can host our 'alpha' site under a different url instead?

#### Pros
- reduce complexity and setup of app
- no password to store and share
- have a 'staging' site for development purposes

#### Cons
- viewers will still be able to view 'staging' site of they stumble across url. (But is that an issue?)

---

2. use something simple like [react-app-protect](https://github.com/bay0/react-app-protect#readme) to provide a simple password challenge

#### Pros
- relatively low effort to implement
- no need for server side / third party service
- no user login required; just provide a password

#### Cons
- not very secure!
- should not use this option if we are planning to set up user login accounts for site

---

3. Implement an auth based solution using a third party service (e.g. auth0 ?)
- TBC. More research and investigation needed to determine pros and cons of this approach

---

## Status : In progress ; Spike on Option 2
The decision is overwhelmingly in favor of implementing password protected for site. see discussion in [this trello card](https://trello.com/c/YU3uyNVL).
- Option 1 is probably ruled out, judging by the comments in the trello discussion
- Option 3 requires more effort to investigate its efficacy and suitability; so it won't be a 'quick fix'
- *Option 2 is probably the least effort; will proceed with a spike on this approach*

**Comment by hqtan** [comment]
@klubiniecki, @k7n4n5t3w4rt,
Please add your discussions in the issue comments

**Comment by klubiniecki** [comment]
Hi! I'm happy with any solution that doesn't show a half-made product under `codeforaustralia.org` domain. We can talk tech here, but it comes down to a "business" decision. 

There is a brand attached to Code For Australia and do people who manage it want a product that looks half-done being accessible to a wider audience? I'd ask Esther.

**Comment by hqtan** [comment]
Hi @klubiniecki ,

The [discussion in the trello card](https://trello.com/c/YU3uyNVL) is in favor of password protection for site, so I'll take an action to try out option 2 with [react-app-protect](https://github.com/bay0/react-app-protect#readme).

Are you cool with that decision, or would you prefer we invest some effort to explore option 3 a bit more?

**Comment by klubiniecki** [comment]
> Hi @klubiniecki ,
> 
> The [discussion in the trello card](https://trello.com/c/YU3uyNVL) is in favor of password protection for site, so I'll take an action to try out option 2 with [react-app-protect](https://github.com/bay0/react-app-protect#readme).
> 
> Are you cool with that decision, or would you prefer we invest some effort to explore option 3 a bit more?

Hey! I think for our purposes (we're not protecting ourselves from being hacked 😄 , but rather having a `work in progress, come back later` UI) we can have a one-line code solution in `App.jsx`.

```
 if (process.env.NODE_ENV === 'production') {
    return <div>Work in progress</div>;
  }
```

We can write up a quick component to display on a production website. This NODE_ENV flag will default to 'production' only on live website, so this won't influence our coding at all.

**Comment by sawks** [comment]
Just jumping in here to confirm that adding a "work in progress" banner or similar until launch is totally sufficient from a Code for Australia perspective. You could also add some copy telling people how to get involved in the project :)

**Comment by klubiniecki** [comment]
> Just jumping in here to confirm that adding a "work in progress" banner or similar until launch is totally sufficient from a Code for Australia perspective. You could also add some copy telling people how to get involved in the project :)

Nice one @sawks, let me write up a Trello card for this task! Sweet! 🚀 

@hqtan Closing the issue and moving implementation details to Trello.
